---
services:
  autobase-console-api:
    image: autobase/console_api:latest
    container_name: autobase-console-api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ansible:/tmp/ansible
    environment:
      - PG_CONSOLE_AUTHORIZATION_TOKEN=${AUTH_TOKEN}
      - PG_CONSOLE_DB_HOST=autobase-console-db
      - PG_CONSOLE_LOGGER_LEVEL=${PG_CONSOLE_LOGGER_LEVEL:-INFO}
      - PG_CONSOLE_DOCKER_IMAGE=autobase/automation:latest
    ports:
      - 8080:8080
    networks:
      - autobase

  autobase-console-ui:
    image: autobase/console_ui:latest
    container_name: autobase-console-ui
    restart: unless-stopped
    environment:
      - PG_CONSOLE_API_URL=/api/v1
      - PG_CONSOLE_AUTHORIZATION_TOKEN=${AUTH_TOKEN}
    ports:
      - 3000:80
    networks:
      - autobase

  autobase-console-db:
    image: autobase/console_db:latest
    container_name: autobase-console-db
    restart: unless-stopped
    volumes:
      - console_postgres:/var/lib/postgresql
    networks:
      - autobase

volumes:
  console_postgres:
    name: console_postgres

networks:
  autobase:
    name: autobase
